// code — the prompt→profile generator, as a Bubble Tea TUI.
//
// Manifest (generated by omp-configured, so this binary stays generic):
//
//	CODE_GENERATED     : generated.plain (facet-grid blocks, keyed by combo id)
//	OMP_AUTH_BROKER_*  : inherited central broker URL, token, and snapshot cache
//	CODE_SELECTION_STATE: optional persisted generator facet choices; empty disables it
//	CODE_AUTH_ACCOUNT_STATE: persisted Manual and named account selections
//	CODE_OMP           : the omp-managed executable for trusted sessions
//	CODE_OMP_UNTRUSTED : the ompu sandbox executable — launched by the u key
package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	clikit "github.com/atyrode/cli-kit"
	"github.com/charmbracelet/bubbles/spinner"
	tea "github.com/charmbracelet/bubbletea"
)

func main() {
	// Subcommands are not TUI sessions; any other argv is still forwarded to
	// the launched omp session as before.
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "generate":
			os.Exit(runGenerate(os.Args[2:]))
		case "session", "sessions":
			os.Exit(runSession(os.Args[2:]))
		case "ls":
			os.Exit(runSession(append([]string{"list"}, os.Args[2:]...)))
		}
	}
	glyphs := defaultGlyphs()
	for _, kv := range strings.Split(os.Getenv("CODE_FACET_GLYPHS"), ",") {
		if p := strings.SplitN(kv, "=", 2); len(p) == 2 && p[1] != "" {
			glyphs[p[0]] = p[1]
		}
	}
	sp := spinner.New()
	sp.Spinner = spinner.Dot
	// The catalog: an explicit CODE_GENERATED wins (the Nix wrapper pre-bakes
	// one); otherwise fall back to where `code generate` writes.
	catalogPath := os.Getenv("CODE_GENERATED")
	if catalogPath == "" {
		catalogPath = defaultCatalogPath()
	}
	generated := loadBlocks(catalogPath)
	broker := resolveBroker(os.Getenv("CODE_AUTH_VAULTS"), os.Getenv("CODE_AUTH_VAULTS_FILE"))
	accountState := os.Getenv("CODE_AUTH_ACCOUNT_STATE")
	accountSelections := loadAccountSelectionState(accountState)
	runtimeTargets := loadRuntimeTargets()
	facets := facetDefs(glyphs)
	if len(runtimeTargets) > 0 {
		facets = append([]facet{runtimeFacet(glyphs["runtime"], runtimeTargets)}, facets...)
	}
	selectionState := os.Getenv("CODE_SELECTION_STATE")
	selection := loadSelectionState(selectionState, facets)
	if len(runtimeTargets) > 0 {
		if _, ok := selection["runtime"]; !ok {
			selection["runtime"] = "hosted"
		}
	}
	// The u key only exists when a sandbox binary does — an explicit
	// CODE_OMP_UNTRUSTED or an ompu on PATH; otherwise hide it from the help
	// and ignore the keypress rather than dying on exec.
	hasSandbox := os.Getenv("CODE_OMP_UNTRUSTED") != ""
	if !hasSandbox {
		_, lookErr := exec.LookPath("ompu")
		hasSandbox = lookErr == nil
	}
	if !hasSandbox {
		keys.Untrusted.SetEnabled(false)
	}
	usageCache := os.Getenv("CODE_USAGE_CACHE")
	cachedAvailability := loadUsageCache(usageCache)
	m := model{
		generated:         generated,
		advisors:          parseAdvisors(generated["__advisors__"]),
		facts:             parseFacts(generated["__models__"]),
		avail:             cachedAvailability,
		broker:            broker,
		usageCache:        usageCache,
		accountState:      accountState,
		accountSelections: accountSelections,
		fetching:          broker.URL != "" && broker.Token != "",
		hadUsage:          cachedAvailability.ok,
		spin:              sp,
		help:              clikit.NewHelp(),
		glyphs:            glyphs,
		runtimeTargets:    runtimeTargets,
		facets:            facets,
		sel:               selection,
		selectionState:    selectionState,
		hasSandbox:        hasSandbox,
	}
	// The catalog decides which dials exist at all; a persisted or default
	// selection must not open on a combo it never generated.
	m.applyCatalog()
	if cachedAvailability.accountsOK {
		m.applyProviderAvailability(connectedPools(cachedAvailability.accounts))
	}
	// First run: no catalog anywhere and no explicit CODE_GENERATED — wrap the
	// TUI in the guided onboarding that builds one (an explicit but broken
	// CODE_GENERATED is an operator config error and is left visible as the
	// usual empty routing panel instead).
	app := tea.Model(m)
	if len(generated) == 0 && os.Getenv("CODE_GENERATED") == "" && len(runtimeTargets) == 0 {
		app = newOnboarding(m)
	}
	// Cell-motion mouse reporting carries wheel events. Filter rejected
	// momentum and unused motion before Bubble Tea's redraw-after-Update loop.
	inputFilter := &wheelInputFilter{}
	final, err := clikit.Run(app, clikit.WithAltScreen(), clikit.WithMouseCellMotion(),
		clikit.WithMessageFilter(inputFilter.Filter))
	if err != nil {
		fmt.Fprintln(os.Stderr, "code:", err)
		os.Exit(1)
	}
	fm, _ := final.(model)
	status := 0
	switch {
	case fm.launchUntrusted:
		status = withSession("sandbox", "CODE_OMP_UNTRUSTED", []string{"ompu"}, func() int {
			return runSandbox("CODE_OMP_UNTRUSTED", []string{"ompu"}, fm.firstPrompt)
		})
	case fm.launchRuntime != "":
		status = withSession("runtime:"+fm.launchRuntime, "CODE_RUNTIME_BROKER", nil, func() int {
			return runRuntimeTarget(fm.launchRuntime, fm.sel["thinking"], fm.firstPrompt)
		})
	case fm.launchManaged:
		status = withSession("managed", "CODE_OMP", []string{"omp-managed", "omp"}, func() int {
			return runTrusted("CODE_OMP", []string{"omp-managed", "omp"}, managedLaunchArgv,
				fm.firstPrompt, fm.broker, fm.accountSelections)
		})
	case fm.genConfig != "":
		status = withSession(comboID(fm.sel, fm.hasRelief), "CODE_OMP", []string{"omp"}, func() int {
			return launchGenerated(fm.genConfig, fm.firstPrompt, fm.broker, fm.accountSelections)
		})
	}
	if status != 0 {
		os.Exit(status)
	}
}

// forwardArgv strips every forwarded profile flag. Trusted launches use OMP's
// ordinary implicit default state; sandbox routing remains owned by ompu.
