// code — the prompt→profile generator, as a Bubble Tea TUI.
//
// Manifest (generated by omp-configured, so this binary stays generic):
//
//	CODE_GENERATED     : generated.plain (facet-grid blocks, keyed by combo id)
//	OMP_AUTH_BROKER_*  : inherited central broker URL, token, and snapshot cache
//	CODE_SELECTION_STATE: relocates the persisted generator facet choices;
//	                      unset uses $XDG_STATE_HOME/code/selection.json, "off" disables
//	CODE_AUTH_ACCOUNT_STATE: persisted Manual and named account selections
//	CODE_AUTH_LOGIN_VIA: optional SSH user@host for central-broker OAuth login
//	CODE_OMP           : the omp-managed executable for trusted sessions
//	CODE_OMP_UNTRUSTED : the ompu sandbox executable — launched by the u key
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	clikit "github.com/atyrode/cli-kit"
	"github.com/charmbracelet/bubbles/spinner"
	tea "github.com/charmbracelet/bubbletea"
)

func main() {
	// Subcommands are not TUI sessions; any other argv is still forwarded to
	// the launched omp session as before.
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "generate":
			os.Exit(runGenerate(os.Args[2:]))
		case "session", "sessions":
			os.Exit(runSession(os.Args[2:]))
		case "worktree", "wt":
			os.Exit(runWorktree(os.Args[2:]))
		case "babel":
			os.Exit(runBabel(os.Args[2:]))
		case sandboxHelperCommand:
			// Code re-entering itself inside its own sandbox. Nothing but the
			// containment backend spawns this, and it is undocumented on
			// purpose: it is an implementation detail of the boundary rather
			// than a command an operator has any use for.
			os.Exit(runSandboxHelper(os.Args[2:]))
		case "ls":
			os.Exit(runSession(append([]string{"list"}, os.Args[2:]...)))
		}
	}
	fm, err := runInteractive(newInteractiveApp(interactiveLaunch))
	if err != nil {
		fmt.Fprintln(os.Stderr, "code:", err)
		os.Exit(1)
	}
	var wt *sessionWorktree
	launchChosen := fm.launchUntrusted || fm.launchRuntime != "" || fm.launchManaged || fm.genConfig != ""
	if fm.worktreeMode && launchChosen {
		wt, err = createSessionWorktree(fm.gitRoot)
		if err != nil {
			fmt.Fprintln(os.Stderr, "code: worktree:", err)
			os.Exit(1)
		}
		wt.ChildDir = filepath.Join(wt.Dir, filepath.FromSlash(fm.gitPrefix))
		if _, err := os.Stat(wt.ChildDir); err != nil {
			wt.ChildDir = wt.Dir
		}
	}
	launchDir := ""
	if wt != nil {
		launchDir = wt.ChildDir
	}

	status := 0
	switch {
	case fm.launchUntrusted:
		// "untrusted", not "sandbox": this is the launcher the operator
		// designated for untrusted sessions, and it contains nothing. The one
		// sandbox in this codebase is the boundary worker mode builds, and the
		// containment declaration is the only thing entitled to that word.
		status = withSession("untrusted", "CODE_OMP_UNTRUSTED", []string{"ompu"}, wt, func() int {
			return runUntrustedLauncher("CODE_OMP_UNTRUSTED", []string{"ompu"}, fm.firstPrompt, launchDir)
		})
	case fm.launchRuntime != "":
		status = withSession("runtime:"+fm.launchRuntime, "CODE_RUNTIME_BROKER", nil, wt, func() int {
			return runRuntimeTarget(fm.launchRuntime, fm.sel["thinking"], fm.firstPrompt, launchDir)
		})
	case fm.launchManaged:
		status = withSession("managed", "CODE_OMP", []string{"omp-managed", "omp"}, wt, func() int {
			return runTrusted("CODE_OMP", []string{"omp-managed", "omp"}, managedLaunchArgv,
				fm.firstPrompt, fm.broker, fm.accountSelections, launchDir)
		})
	case fm.genConfig != "":
		status = withSession(comboID(fm.sel, fm.hasRelief), "CODE_OMP", []string{"omp"}, wt, func() int {
			return launchGenerated(fm.genConfig, fm.firstPrompt, fm.broker, fm.accountSelections, launchDir)
		})
	}
	if wt != nil {
		releaseSessionWorktree(wt)
	}
	if status != 0 {
		os.Exit(status)
	}
}

// interactiveMode says what confirming a selection means. The dial UI is the
// same either way — that it is the same UI is the whole point of the
// configuration ceremony (babelconfigure.go) — but a launch hands the selection
// to omp, while a ceremony mints an immutable profile revision out of it and
// hands Babel the reference. The keys that only make sense for a launch are
// inert in the latter, and the environment is not allowed to decide which dials
// the operator is shown.
type interactiveMode int

const (
	interactiveLaunch interactiveMode = iota
	interactiveConfigure
)

// newInteractiveApp builds the dial TUI from Code's own state: the catalog, the
// usage broker, the runtime targets and the persisted dial position. It returns
// the app to mount, which is the generator itself — or, on a machine with no
// catalog at all, the onboarding shell that builds one and then hands off to it.
func newInteractiveApp(mode interactiveMode) tea.Model {
	glyphs := defaultGlyphs()
	for _, kv := range strings.Split(os.Getenv("CODE_FACET_GLYPHS"), ",") {
		if p := strings.SplitN(kv, "=", 2); len(p) == 2 && p[1] != "" {
			glyphs[p[0]] = p[1]
		}
	}
	sp := spinner.New()
	sp.Spinner = spinner.Dot
	// The catalog: an explicit CODE_GENERATED wins (the Nix wrapper pre-bakes
	// one); otherwise fall back to where `code generate` writes.
	catalogPath := os.Getenv("CODE_GENERATED")
	if catalogPath == "" {
		catalogPath = defaultCatalogPath()
	}
	generated := loadBlocks(catalogPath)
	broker := resolveBroker(os.Getenv("CODE_AUTH_VAULTS"), os.Getenv("CODE_AUTH_VAULTS_FILE"))
	accountState := os.Getenv("CODE_AUTH_ACCOUNT_STATE")
	accountSelections := loadAccountSelectionState(accountState)
	runtimeTargets := loadRuntimeTargets()
	facets := facetDefs(glyphs)
	if len(runtimeTargets) > 0 {
		facets = append([]facet{runtimeFacet(glyphs["runtime"], runtimeTargets)}, facets...)
	}
	// The interactive run is the only thing that writes a selection, and worker
	// mode under Babel is the caller that most needs to read one, so an unset
	// variable now means the default location rather than statelessness — and an
	// override, which the worker can never be told about, is mirrored there too.
	selectionState, selectionHandoff := selectionStateTargets()
	if mode == interactiveConfigure {
		// The ceremony reads and writes the default location and nothing else.
		// CODE_SELECTION_STATE is a variable anything in the process tree can
		// set, so honouring it here would let a dial position nobody in the
		// room chose be the one the operator is asked to confirm — and the
		// profile minted from it would carry that confirmation into every
		// receipt (atyrode/babel#86). The default location is where an
		// interactive `code` writes, so the ceremony still opens on the dials
		// this operator last turned and leaves them where the next `code`
		// finds them.
		selectionState, selectionHandoff = defaultSelectionStatePath(), ""
	}
	selection := loadSelectionState(selectionState, facets)
	if len(runtimeTargets) > 0 {
		if _, ok := selection["runtime"]; !ok {
			selection["runtime"] = "hosted"
		}
	}
	// The u key only exists when a sandbox binary does — an explicit
	// CODE_OMP_UNTRUSTED or an ompu on PATH; otherwise hide it from the help
	// and ignore the keypress rather than dying on exec.
	hasSandbox := os.Getenv("CODE_OMP_UNTRUSTED") != ""
	if !hasSandbox {
		_, lookErr := exec.LookPath("ompu")
		hasSandbox = lookErr == nil
	}
	if !hasSandbox {
		keys.Untrusted.SetEnabled(false)
	}
	keys.Worktree.SetEnabled(false)
	if mode == interactiveConfigure {
		// A ceremony ends in a profile or in nothing. The launch keys mint no
		// profile, so they are inert here rather than quietly starting a
		// session Babel is holding the terminal open for; Enter is relabelled
		// because it is now the only key that ends this run with a
		// configuration.
		keys.Managed.SetEnabled(false)
		keys.Untrusted.SetEnabled(false)
		keys.Launch.SetHelp("⏎", "confirm")
	}
	usageCache := os.Getenv("CODE_USAGE_CACHE")
	cachedAvailability := loadUsageCache(usageCache)
	m := model{
		generated:         generated,
		advisors:          parseAdvisors(generated["__advisors__"]),
		facts:             parseFacts(generated["__models__"]),
		avail:             cachedAvailability,
		broker:            broker,
		usageCache:        usageCache,
		accountState:      accountState,
		accountSelections: accountSelections,
		fetching:          broker.URL != "" && broker.Token != "",
		hadUsage:          cachedAvailability.ok,
		spin:              sp,
		help:              clikit.NewHelp(),
		glyphs:            glyphs,
		runtimeTargets:    runtimeTargets,
		facets:            facets,
		sel:               selection,
		selectionState:    selectionState,
		selectionHandoff:  selectionHandoff,
		hasSandbox:        hasSandbox,
		configuring:       mode == interactiveConfigure,
	}
	// The catalog decides which dials exist at all; a persisted or default
	// selection must not open on a combo it never generated.
	m.applyCatalog()
	if cachedAvailability.accountsOK {
		m.applyProviderAvailability(connectedPools(cachedAvailability.accounts))
	}
	// First run: no catalog anywhere and no explicit CODE_GENERATED — wrap the
	// TUI in the guided onboarding that builds one (an explicit but broken
	// CODE_GENERATED is an operator config error and is left visible as the
	// usual empty routing panel instead).
	if len(generated) == 0 && os.Getenv("CODE_GENERATED") == "" && len(runtimeTargets) == 0 {
		return newOnboarding(m)
	}
	return m
}

// runInteractive mounts the app and returns the generator's end state. The final
// model is what every caller reads its answer from — which session to launch, or
// which dials were confirmed — so the type assertion lives here rather than at
// each call site.
func runInteractive(app tea.Model) (model, error) {
	// Cell-motion mouse reporting carries wheel events. Filter rejected
	// momentum and unused motion before Bubble Tea's redraw-after-Update loop.
	inputFilter := &wheelInputFilter{}
	final, err := clikit.Run(app, clikit.WithAltScreen(), clikit.WithMouseCellMotion(),
		clikit.WithMessageFilter(inputFilter.Filter))
	if err != nil {
		return model{}, err
	}
	fm, _ := final.(model)
	return fm, nil
}

// forwardArgv strips every forwarded profile flag. Trusted launches use OMP's
// ordinary implicit default state; sandbox routing remains owned by ompu.
